version: "3.9"
    
services:
  
  nginx:
    depends_on:
      - known
    image: nginx:latest
    networks:
      - frontend
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - web:/var/www/html
  
  known:
    depends_on:
      - known-db
    environment:
      - KNOWN_MYSQL_PASSWORD=${KNOWN_MYSQL_PASSWORD}
    image: wescran/known-php-fpm:latest
    links:
      - known-db:mysql
    networks:
      - frontend
      - backend
    restart: always
    volumes:
      - data:/var/www/html/Uploads
      - web:/var/www/html
  
  known-db:
    environment:
      - MYSQL_DATABASE=known
      - MYSQL_USER=known
      - MYSQL_PASSWORD=${KNOWN_MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${KNOWN_MYSQL_PASSWORD}
    image: mariadb:latest
    networks:
      - backend
    restart: always
    volumes:
      - db:/var/lib/mysql

networks:
  frontend:
  backend:

volumes:
  db:
  data:
  web:
